include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 80

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_final_fields: true
    sort_constructors_first: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_positional_boolean_parameters: true
    prefer_typing_uninitialized_variables: true
    type_annotate_public_apis: true