name: webfabrik_theme
description: "A Flutter theme package that provides a cohesive, iOS-inspired design system with predefined styles, spacing, and custom widgets to create beautiful and consistent user interfaces."
version: 0.0.1
repository: "https://github.com/ton-An/webfabrik_theme"

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  gap: ^3.0.1
  smooth_corner: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
