name: webfabrik_theme
description: "A Flutter theme package that provides a cohesive, iOS-inspired design system with predefined styles, spacing, and custom widgets to create beautiful and consistent user interfaces."
version: 0.0.1
repository: "https://github.com/ton-An/webfabrik_theme"

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  gap: ^3.0.1
  pointer_interceptor: ^0.10.1+2
  smooth_corner: ^1.1.1
  dotted_line: ^3.2.3
  go_router: ^16.2.0
  link_text: ^0.2.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  gradient_borders: ^1.0.2
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true

  assets:
    - assets/images/logos/